// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package ssh2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorNone-0]
	_ = x[ErrorSocketNone - -1]
	_ = x[ErrorBannerRecv - -2]
	_ = x[ErrorBannerSend - -3]
	_ = x[ErrorInvalidMac - -4]
	_ = x[ErrorKexFailure - -5]
	_ = x[ErrorAlloc - -6]
	_ = x[ErrorSocketSend - -7]
	_ = x[ErrorKeyExchangeFailure - -8]
	_ = x[ErrorTimeout - -9]
	_ = x[ErrorHostKeyInit - -10]
	_ = x[ErrorHostKeySign - -11]
	_ = x[ErrorDecrypt - -12]
	_ = x[ErrorSocketDisconnect - -13]
	_ = x[ErrorProto - -14]
	_ = x[ErrorPasswordExpired - -15]
	_ = x[ErrorFile - -16]
	_ = x[ErrorMethodNone - -17]
	_ = x[ErrorAuthenticationFailed - -18]
	_ = x[ErrorPublickeyUnrecognized - -18]
	_ = x[ErrorPublickeyUnverified - -19]
	_ = x[ErrorChannelOutoforder - -20]
	_ = x[ErrorChannelFailure - -21]
	_ = x[ErrorChannelRequestDenied - -22]
	_ = x[ErrorChannelUnknown - -23]
	_ = x[ErrorChannelWindowExceeded - -24]
	_ = x[ErrorChannelPacketExceeded - -25]
	_ = x[ErrorChannelClosed - -26]
	_ = x[ErrorChannelEofSent - -27]
	_ = x[ErrorScpProtocol - -28]
	_ = x[ErrorZlib - -29]
	_ = x[ErrorSocketTimeout - -30]
	_ = x[ErrorSftpProtocol - -31]
	_ = x[ErrorRequestDenied - -32]
	_ = x[ErrorMethodNotSupported - -33]
	_ = x[ErrorInval - -34]
	_ = x[ErrorInvalidPollType - -35]
	_ = x[ErrorPublickeyProtocol - -36]
	_ = x[ErrorEagain - -37]
	_ = x[ErrorBufferTooSmall - -38]
	_ = x[ErrorBadUse - -39]
	_ = x[ErrorCompress - -40]
	_ = x[ErrorOutOfBoundary - -41]
	_ = x[ErrorAgentProtocol - -42]
	_ = x[ErrorSocketRecv - -43]
	_ = x[ErrorEncrypt - -44]
	_ = x[ErrorBadSocket - -45]
	_ = x[ErrorKnownHosts - -46]
	_ = x[ErrorChannelWindowFull - -47]
	_ = x[ErrorKeyfileAuthFailed - -48]
	_ = x[ErrorRandgen - -49]
	_ = x[ErrorMissingUserauthBanner - -50]
	_ = x[ErrorAlgoUnsupported - -51]
	_ = x[ErrorMacFailure - -52]
	_ = x[ErrorHashInit - -53]
	_ = x[ErrorHashCalc - -54]
	_ = x[ErrorBannerNone - -2]
}

const _ErrorCode_name = "ErrorHashCalcErrorHashInitErrorMacFailureErrorAlgoUnsupportedErrorMissingUserauthBannerErrorRandgenErrorKeyfileAuthFailedErrorChannelWindowFullErrorKnownHostsErrorBadSocketErrorEncryptErrorSocketRecvErrorAgentProtocolErrorOutOfBoundaryErrorCompressErrorBadUseErrorBufferTooSmallErrorEagainErrorPublickeyProtocolErrorInvalidPollTypeErrorInvalErrorMethodNotSupportedErrorRequestDeniedErrorSftpProtocolErrorSocketTimeoutErrorZlibErrorScpProtocolErrorChannelEofSentErrorChannelClosedErrorChannelPacketExceededErrorChannelWindowExceededErrorChannelUnknownErrorChannelRequestDeniedErrorChannelFailureErrorChannelOutoforderErrorPublickeyUnverifiedErrorAuthenticationFailedErrorMethodNoneErrorFileErrorPasswordExpiredErrorProtoErrorSocketDisconnectErrorDecryptErrorHostKeySignErrorHostKeyInitErrorTimeoutErrorKeyExchangeFailureErrorSocketSendErrorAllocErrorKexFailureErrorInvalidMacErrorBannerSendErrorBannerRecvErrorSocketNoneErrorNone"

var _ErrorCode_index = [...]uint16{0, 13, 26, 41, 61, 87, 99, 121, 143, 158, 172, 184, 199, 217, 235, 248, 259, 278, 289, 311, 331, 341, 364, 382, 399, 417, 426, 442, 461, 479, 505, 531, 550, 575, 594, 616, 640, 665, 680, 689, 709, 719, 740, 752, 768, 784, 796, 819, 834, 844, 859, 874, 889, 904, 919, 928}

func (i ErrorCode) String() string {
	i -= -54
	if i < 0 || i >= ErrorCode(len(_ErrorCode_index)-1) {
		return "ErrorCode(" + strconv.FormatInt(int64(i+-54), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
