// Code generated by "stringer -type=SftpErrorCode"; DO NOT EDIT.

package ssh2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FX_OK-0]
	_ = x[FX_EOF-1]
	_ = x[FX_NO_SUCH_FILE-2]
	_ = x[FX_PERMISSION_DENIED-3]
	_ = x[FX_FAILURE-4]
	_ = x[FX_BAD_MESSAGE-5]
	_ = x[FX_NO_CONNECTION-6]
	_ = x[FX_CONNECTION_LOST-7]
	_ = x[FX_OP_UNSUPPORTED-8]
	_ = x[FX_INVALID_HANDLE-9]
	_ = x[FX_NO_SUCH_PATH-10]
	_ = x[FX_FILE_ALREADY_EXISTS-11]
	_ = x[FX_WRITE_PROTECT-12]
	_ = x[FX_NO_MEDIA-13]
	_ = x[FX_NO_SPACE_ON_FILESYSTEM-14]
	_ = x[FX_QUOTA_EXCEEDED-15]
	_ = x[FX_UNKNOWN_PRINCIPAL-16]
	_ = x[FX_LOCK_CONFLICT-17]
	_ = x[FX_DIR_NOT_EMPTY-18]
	_ = x[FX_NOT_A_DIRECTORY-19]
	_ = x[FX_INVALID_FILENAME-20]
	_ = x[FX_LINK_LOOP-21]
}

const _SftpErrorCode_name = "FX_OKFX_EOFFX_NO_SUCH_FILEFX_PERMISSION_DENIEDFX_FAILUREFX_BAD_MESSAGEFX_NO_CONNECTIONFX_CONNECTION_LOSTFX_OP_UNSUPPORTEDFX_INVALID_HANDLEFX_NO_SUCH_PATHFX_FILE_ALREADY_EXISTSFX_WRITE_PROTECTFX_NO_MEDIAFX_NO_SPACE_ON_FILESYSTEMFX_QUOTA_EXCEEDEDFX_UNKNOWN_PRINCIPALFX_LOCK_CONFLICTFX_DIR_NOT_EMPTYFX_NOT_A_DIRECTORYFX_INVALID_FILENAMEFX_LINK_LOOP"

var _SftpErrorCode_index = [...]uint16{0, 5, 11, 26, 46, 56, 70, 86, 104, 121, 138, 153, 175, 191, 202, 227, 244, 264, 280, 296, 314, 333, 345}

func (i SftpErrorCode) String() string {
	if i < 0 || i >= SftpErrorCode(len(_SftpErrorCode_index)-1) {
		return "SftpErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SftpErrorCode_name[_SftpErrorCode_index[i]:_SftpErrorCode_index[i+1]]
}
